apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: lidiyahanicheva/hello-gitops
  newTag: dc9b9ed59a72dd5b0536a7adcd1bde90132e8965
namePrefix: blue-
